### PR TITLE
Roc data collector

### PR DESCRIPTION
**Pull request by jkvas**
new datacollector, which merges events from AHCAL, ECAL and BIF (and desy table as well). This datacollector expects complete readout cycles

### CODE REVIEW

**Comment by airqui** [comment]
Hi @jkvas 
I have accepted it but when running, it crashes.
I have changed the producer names and the mandatory producers to be in the data steam but it still crashing...


Has the BIF to be always mandatory ?

**Comment by jkvas** [comment]
hi @airqui,
I think the problem is the name of the ecal data collector, which was not set in the startup script. I used **ECAL1** instead of **SiWECALProducer**.The data collector is started with:

`xterm -sb -sl 100000 -geometry 80x4 -T "ROC Collector 1" -e "${eudaq_bin}/euCliCollector -n CaliceROCDataCollector -t dc_roc -r tcp://${RUNCONTROLIP}:${RPCPORT} |tee -a data/logs/dc_roc_${currentdate}.log ; read "&
`

and the config section:
```
[DataCollector.dc_roc]
EUDAQ_FW_PATTERN = "data/ROCreprocess_run_$6R_tp$X"
DISABLE_PRINT = 1
MandatoryBif = 0
EUDAQ_FW=native

[Producer.ECAL1]
EUDAQ_DC = dc_roc
...
[Producer.AHCAL1]
EUDAQ_DC = dc_roc
...
```
The **MandatoryBif** should be irrelevant, since the bif does not connect to the data collector. The datacollector checks which producers are connected (according to their names) and if some producers are not connected, they are ignored

**Comment by airqui** [comment]
I made these  changes.
It runs okay if I only have the SiWECAL in the run (making the ahcal not mandatory).
If I have the AHCAL only, it doesn't work. My guess is that: a) I don't have the latest producer b) I am missing some setting parameters for the AHCAL producer

**Comment by jkvas** [comment]
Hi @airqui, I reproduced the problem - it must be something in the datacollecter. I will find out

**Comment by jkvas** [comment]
Interesting, now it does not work at all. Crashes after the start immediately. Investigating

**Comment by jkvas** [comment]
Observations so far: 
 - crash happens when the ECAL has more event  than AHCAL and AHCAL queue gets empty
 - possibly wrong mutex (should go to DoReceive() instead of BuildEvent_roc() )

**Comment by jkvas** [comment]
Bug is found and 100% understood. Patch is coming soom.

**Comment by airqui** [comment]
great!

**Pull request merged**
